function main(action)
if nargin<1
    clear;clc;
    action="start";
end
switch action
    case "start"
        offset= [0.05 0.4 -0.1 0];
        PosEHeight = [0.1 0.1 0.2 0.4];
        PosEHText = PosEHeight + offset;
        PosEWidth = [0.4 0.1 0.2 0.4];
        PosEWText = PosEWidth + offset;
        PosGen = [0.7 0.1 0.2 0.4];
        PosExit = PosGen + offset;
        fig=figure('Name','Mapa','NumberTitle','off',...
        'Position',[200 100 594 65],'Resize','off');
        data.HeightEdit=uicontrol('Style','edit', ...
            'Units','normalized', ...
            'Position',PosEHeight,...
            'String','15');
        uicontrol('Style','text',...
            'Units','normalized', ...
            'Position',PosEHText,...
            'String','Vyska');
        data.WidthEdit=uicontrol('Style','edit', ...
            'Units','normalized', ...
            'Position',PosEWidth,...
            'String','15');
        uicontrol('Style','text',...
            'Units','normalized', ...
            'Position',PosEWText,...
            'String','Sirka');
        data.ExitButton=uicontrol('Style','push', ...
            'Units','normalized', ...
            'Position',PosExit, ...
            'String','KONEC', ...
            'FontWeight','bold',...
            'ForegroundColor',[1 0 0],...
            'Callback','main(''close'')');
        data.GenerateButton=uicontrol('Style','push', ...
            'Units','normalized', ...
            'Position',PosGen, ...
            'String','GENERUJ', ...
            'FontWeight','bold',...
            'ForegroundColor',[0 0 0],...
            'Callback','main(''logic'')');
        set(fig,'UserData',data);
    case "close"
        close gcf;
        if numel(findall(groot,'Type','figure','Name','Vykres'))==1
            figure(findall(groot,'Type','figure','Name','Vykres'));
            close gcf;
        end
    case "logic"
        data=get(gcf,'UserData');
        Height=uint16(str2double(data.HeightEdit.String));
        Width=uint16(str2double(data.WidthEdit.String));
        if(Height>0 && Width >0)
            out = Bitmapovator(template(Height,Width));
            imwrite(out,"./test.png")
            if numel(findall(groot,'Type','figure','Name','Vykres'))~=1
                figure('Name','Vykres','NumberTitle','off');
                image(out);
            else
                figure(findall(groot,'Type','figure','Name','Vykres'));
                image(out);
            end
        else
            error("invalid input");
        end
end